export const getEmployeeData = [
    {
        _id: '65e1814b3f4bf51dfe696ebe',
        index: 0,
        guid: '052a0e05-bffa-4d8a-80f9-24a86ff33643',
        isActive: true,
        balance: '$3,183.30',
        picture: 'http://placehold.it/32x32',
        age: 40,
        eyeColor: 'green',
        name: 'Cherry Jimenez',
        gender: 'female',
        company: 'PAPRIKUT',
        email: 'cherryjimenez@paprikut.com',
        phone: '+1 (948) 519-3453',
        address: '720 Glenwood Road, Hatteras, Wisconsin, 5569',
        about: 'Adipisicing ipsum ad laborum Lorem nulla enim. Tempor culpa minim culpa voluptate sunt. Ut cupidatat sint excepteur officia. Qui culpa id id veniam cillum.\r\n',
        registered: '2017-11-16T04:27:24 -08:00',
        latitude: 66.920399,
        longitude: 25.908515,
        tags: ['adipisicing', 'pariatur', 'ullamco', 'labore', 'aliqua', 'nisi', 'cillum'],
        friends: [
            {
                id: 0,
                name: 'Fulton Elliott',
            },
            {
                id: 1,
                name: 'Eaton Boone',
            },
            {
                id: 2,
                name: 'Ana Clarke',
            },
        ],
        greeting: 'Hello, Cherry Jimenez! You have 3 unread messages.',
        favoriteFruit: 'strawberry',
    },
    {
        _id: '65e1814b650f608d2613bc9e',
        index: 1,
        guid: '9525f740-3f41-4684-9960-e3f838d6e39c',
        isActive: true,
        balance: '$1,923.14',
        picture: 'http://placehold.it/32x32',
        age: 23,
        eyeColor: 'blue',
        name: 'Lilly Goff',
        gender: 'female',
        company: 'HOUSEDOWN',
        email: 'lillygoff@housedown.com',
        phone: '+1 (855) 578-2927',
        address: '427 Kingsway Place, Ypsilanti, Oregon, 2507',
        about: 'Consequat nisi laboris in consequat eiusmod deserunt duis esse ullamco. Nostrud aliquip cupidatat consectetur nostrud consectetur est adipisicing non dolore culpa exercitation. Nostrud aliquip nisi duis nostrud nulla. Velit cillum voluptate sint cillum occaecat adipisicing magna quis minim pariatur elit laboris commodo. Nulla est Lorem ut est ea officia esse tempor. Reprehenderit sint esse non nostrud fugiat amet adipisicing. Ut ut culpa ipsum minim voluptate sit.\r\n',
        registered: '2021-09-13T04:08:55 -08:00',
        latitude: -85.424042,
        longitude: 80.97398,
        tags: ['duis', 'proident', 'occaecat', 'non', 'minim', 'minim', 'quis'],
        friends: [
            {
                id: 0,
                name: 'Mcclure Moreno',
            },
            {
                id: 1,
                name: 'Mcdowell Booker',
            },
            {
                id: 2,
                name: 'Natalie Peters',
            },
        ],
        greeting: 'Hello, Lilly Goff! You have 10 unread messages.',
        favoriteFruit: 'strawberry',
    },
    {
        _id: '65e1814b82f2fe530566b33e',
        index: 2,
        guid: 'ed2057f0-d986-41e7-80fe-ef38122042d0',
        isActive: false,
        balance: '$3,592.46',
        picture: 'http://placehold.it/32x32',
        age: 28,
        eyeColor: 'brown',
        name: 'Lucia Reese',
        gender: 'female',
        company: 'CHILLIUM',
        email: 'luciareese@chillium.com',
        phone: '+1 (947) 435-3828',
        address: '606 Union Avenue, Bluffview, Kentucky, 2870',
        about: 'Tempor dolor ullamco aute sint dolor occaecat labore anim eiusmod voluptate. Non ea eu mollit sunt deserunt. Exercitation pariatur id in est ut laboris veniam quis ea sint proident dolore mollit eiusmod. Elit ipsum ipsum dolore sit esse ipsum incididunt nostrud sint enim ea sit. Deserunt nostrud nostrud aute enim est dolore aliquip nostrud fugiat.\r\n',
        registered: '2014-06-27T03:54:27 -08:00',
        latitude: -77.690906,
        longitude: -33.859758,
        tags: ['exercitation', 'sit', 'do', 'laboris', 'esse', 'quis', 'dolor'],
        friends: [
            {
                id: 0,
                name: 'Debra Hurley',
            },
            {
                id: 1,
                name: 'Bonita Shaffer',
            },
            {
                id: 2,
                name: 'Stevens Cooley',
            },
        ],
        greeting: 'Hello, Lucia Reese! You have 4 unread messages.',
        favoriteFruit: 'banana',
    },
    {
        _id: '65e1814bcd65e0e317c59926',
        index: 3,
        guid: '7499f5c4-1343-4fec-8c1e-f731d4507331',
        isActive: false,
        balance: '$2,604.42',
        picture: 'http://placehold.it/32x32',
        age: 29,
        eyeColor: 'brown',
        name: 'Figueroa Randall',
        gender: 'male',
        company: 'GONKLE',
        email: 'figueroarandall@gonkle.com',
        phone: '+1 (937) 556-2736',
        address: '946 Bartlett Place, Rehrersburg, Ohio, 6871',
        about: 'Cupidatat quis ullamco fugiat incididunt tempor aliqua ipsum mollit quis ex cupidatat ad reprehenderit. Commodo qui eu occaecat dolor cillum fugiat laboris officia velit dolore. Tempor velit minim et irure consequat cillum occaecat ea ullamco. Ipsum fugiat exercitation ad aliqua id ut ut irure officia pariatur sit non excepteur mollit.\r\n',
        registered: '2015-08-20T11:39:40 -08:00',
        latitude: 89.581436,
        longitude: 5.127067,
        tags: ['veniam', 'quis', 'tempor', 'reprehenderit', 'laborum', 'nostrud', 'et'],
        friends: [
            {
                id: 0,
                name: 'Jeanie Johnson',
            },
            {
                id: 1,
                name: 'Flowers Hester',
            },
            {
                id: 2,
                name: 'Horton Contreras',
            },
        ],
        greeting: 'Hello, Figueroa Randall! You have 8 unread messages.',
        favoriteFruit: 'apple',
    },
    {
        _id: '65e1814b66b83a5a1077164b',
        index: 4,
        guid: 'fdbeba1e-de03-461a-b0a1-8408597ffde3',
        isActive: true,
        balance: '$3,113.83',
        picture: 'http://placehold.it/32x32',
        age: 38,
        eyeColor: 'brown',
        name: 'Roy Riley',
        gender: 'male',
        company: 'ZIDANT',
        email: 'royriley@zidant.com',
        phone: '+1 (803) 495-2014',
        address: '747 Meserole Street, Vandiver, American Samoa, 3927',
        about: 'Nulla deserunt ullamco voluptate pariatur. Duis laboris officia reprehenderit nostrud. Et consectetur exercitation exercitation culpa exercitation nisi veniam est dolor. Id minim fugiat exercitation culpa sunt anim laborum. Consectetur labore ullamco culpa pariatur pariatur aute. Quis et cillum non voluptate aliquip veniam exercitation culpa aliquip elit cillum sunt voluptate fugiat.\r\n',
        registered: '2019-12-28T10:11:17 -08:00',
        latitude: -81.663762,
        longitude: 7.994188,
        tags: ['magna', 'duis', 'do', 'pariatur', 'velit', 'deserunt', 'officia'],
        friends: [
            {
                id: 0,
                name: 'Berger Church',
            },
            {
                id: 1,
                name: 'Hancock Mann',
            },
            {
                id: 2,
                name: 'Donovan Walton',
            },
        ],
        greeting: 'Hello, Roy Riley! You have 1 unread messages.',
        favoriteFruit: 'banana',
    },
]
